### ISSUE TITLE
Possible to sign the nuget package you publish over nuget.org?

### ISSUE THREAD

**Issue by zadigus** [DerekGn/HexIO#3]
I am trying to make use of your code within my codebase, where I produce NuGet packages which are all signed. Now, I'd like to install your nuget in one of my projects and I can't because it is not signed. I get the following error:
```bash
Referenced assembly 'HexIO, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```
Would that be an option for you to sign your package?

**Comment by DerekGn** [comment]
Yes I can sign the package, I will do it over the next day or two.

**Comment by DerekGn** [comment]
I have signed the assembly which should be all that is needed to resolve the error that you are seeing. The new package is version is 2.0.0. It is available from nuget.org https://www.nuget.org/packages/HexIO/2.0.0
