### ISSUE TITLE
IntelHexRecordExtensions should public

### ISSUE THREAD

**Issue by rqx110** [DerekGn/HexIO#4]
the extension method should be public, or can't use it from outside. 
e.g.  the demo code in readme `data.ToHexString()`
https://github.com/DerekGn/HexIO/blob/ae39108b7816c2421b2661846f97661271245412/Src/HexIO/IntelHexRecordExtensions.cs#L32

**Comment by DerekGn** [comment]
I have moved and simplified the method it will be available in next version on nuget
