### ISSUE TITLE
New Feature 

### ISSUE THREAD

**Issue by alexelenter-99** [DerekGn/HexIO#6]
Hi! 

I've used this Nuget Package and it worked like a charm. I added a funcionnality to parse an hexFile, modify it by address and then write it again.
I'm more than happy to contribute to the project by making a pull request. 

Hope I can help,
Alex.

**Comment by DerekGn** [comment]
Hi Alex,

Yes you can open a PR and we can review the changes.

Derek

**Comment by DerekGn** [comment]
I have added a transformer class in V3.0
