### ISSUE TITLE
Impossible to write record type 3 (start segment address)?

### ISSUE THREAD

**Issue by AppyxDaniel** [DerekGn/HexIO#8]
It seems impossible to write a record of type 3 (start segment address) since the AddressType enum does not contain a definition for this type. An ArgumentOutOfRangeException is the result.

Reading this record type seems to work.

**Comment by DerekGn** [comment]
This might simply be an oversight on my part, TBH i cant remember I wrote this a long time ago and I was using it with ARM flash images which did not need the start segment address. I will take a look.

**Comment by DerekGn** [comment]
Ok I checked the history and that record type was never supported in the original version.
I think this library could do with a bit of a refactor as I see a few improvements that I should have made way back when.
I will add support for the additional record type.

**Comment by DerekGn** [comment]
@AppyxDaniel Check out version 3.0 on this branch https://github.com/DerekGn/HexIO/tree/v3.0

**Comment by AppyxDaniel** [comment]
@DerekGn It looks good to me. I did not test the changes to be honest but I took a look at the code changes.

**Comment by DerekGn** [comment]
I have one more feature to add which is an hex file modifier based on matches. I will be adding this and then generating a release 3.0
